// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HouseRentDbContext))]
    [Migration("20251025174312_AddInit")]
    partial class AddInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLongTerm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HouseId = 1,
                            IsLongTerm = false,
                            StartDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 200m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HouseId = 2,
                            IsLongTerm = true,
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 2100m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPool")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLongTermAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPetsAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShortTermAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmokingAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<int?>("MinMonths")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilitiesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UtilitiesIncluded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Country Lane",
                            Area = 80.0,
                            CheckInTime = new TimeSpan(0, 14, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 12, 0, 0, 0),
                            City = "Kyiv",
                            Country = "Ukraine",
                            DepositAmount = 200m,
                            Description = "A small cozy house in the countryside.",
                            HasAirConditioning = false,
                            HasParking = true,
                            HasPool = false,
                            HasWifi = true,
                            IsLongTermAvailable = true,
                            IsPetsAllowed = true,
                            IsShortTermAvailable = true,
                            IsSmokingAllowed = false,
                            MaxGuests = 4,
                            MinMonths = 1,
                            OwnerId = 1,
                            PricePerMonth = 1000m,
                            PricePerNight = 50m,
                            Rating = 4.5,
                            Rooms = 3,
                            Title = "Cozy Cottage",
                            UtilitiesDescription = "Water, electricity, internet",
                            UtilitiesIncluded = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Main Street",
                            Area = 60.0,
                            CheckInTime = new TimeSpan(0, 0, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 0, 0, 0, 0),
                            City = "Lviv",
                            Country = "Ukraine",
                            Description = "A modern apartment in the city center.",
                            HasAirConditioning = true,
                            HasParking = false,
                            HasPool = false,
                            HasWifi = true,
                            IsLongTermAvailable = false,
                            IsPetsAllowed = false,
                            IsShortTermAvailable = true,
                            IsSmokingAllowed = false,
                            MaxGuests = 3,
                            OwnerId = 2,
                            PricePerNight = 70m,
                            Rating = 0.0,
                            Rooms = 2,
                            Title = "Modern Apartment",
                            UtilitiesIncluded = false
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.HouseImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("HouseImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HouseId = 1,
                            ImageUrl = "https://example.com/house1-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            HouseId = 1,
                            ImageUrl = "https://example.com/house1-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            HouseId = 2,
                            ImageUrl = "https://example.com/house2-1.jpg"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Great place!",
                            HouseId = 1,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Very cozy.",
                            HouseId = 1,
                            Rating = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Booking", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.House", "House")
                        .WithMany("Bookings")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.House", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.User", "Owner")
                        .WithMany("OwnedHouses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.User", "Tenant")
                        .WithMany("RentedHouses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.HouseImage", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.House", "House")
                        .WithMany("Images")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Review", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.House", "House")
                        .WithMany("Reviews")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.House", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("OwnedHouses");

                    b.Navigation("RentedHouses");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
